### ISSUE TITLE
Facebook login error

### ISSUE THREAD

**Issue by drewwilliams** [DevProgress/hill-a-ride#1]
Getting the following error when trying to login with Facebook via either button on http://areyouwithher.herokuapp.com/login:

“Can't Load URL: The domain of this URL isn't included in the app's domains. To be able to load this URL, add all domains and subdomains of your app to the App Domains field in your app settings.”

Mobile Safari on iOS (iOS 9.3.2) on an iPad.

**Comment by uberdog** [comment]
I get the same. It's thrown by Facebook on this URL.

https://www.facebook.com/v2.6/dialog/oauth?client_id=478523429024173&redirect_uri=http%3A%2F%2Fareyouwithher.herokuapp.com%2Fauth%2Ffacebook%2Fcallback&response_type=code&scope=public_profile%2C+email%2C+user_friends&state=502dc6a6080eeef9c2b33a9eddc7a8fd25b84b9893f3f342

**Comment by spunyasena** [comment]
Fixed the setting on the FB app. It should work now!
